### ISSUE TITLE
PHP 8.1 compatibility

### ISSUE THREAD

**Issue by boboldehampsink** [MegaChriz/afasprofit#5] opened 2022-04-05 11:15 UTC
On PHP 8.1 it fails with the following errror:

`Undefined property: Afas\Component\Soap\SoapClient::$uri`

**Comment by MegaChriz** [comment] 2022-04-06 08:59
Thanks for the report! I have opened branch [202204_php81_support](https://github.com/MegaChriz/afasprofit/tree/202204_php81_support) for enabling PHP 8.1 testing. So far, the automated tests don't catch the error:
https://app.travis-ci.com/github/MegaChriz/afasprofit/jobs/566056054

It does report a bunch of deprecation warnings. Some of them I've just fixed, but all others are in dependencies.

Do you want to write a test that catches the reported error?

**Comment by boboldehampsink** [comment] 2022-04-07 12:43
Are you not able to reproduce the problem on a 8.1 environment? Just the "Get data from Profit (GetConnector)" example fails already on 8.1. I have tested this on multiple environments with 8.1

**Comment by boboldehampsink** [comment] 2022-07-05 11:42
bump

**Comment by MegaChriz** [comment] 2022-07-05 11:45
I didn't had a PHP 8.1 environment yet to test with, but I do now. I put testing PHP 8.1 in my agenda. But I still think it would be useful to have this error be catched by a test.

**Comment by MegaChriz** [comment] 2022-07-12 09:18
I had a look at it and I could reproduce the issue. But I don't know right away how to fix it. Simply removing the line from `Afas\Component\Soap\SoapClient::__doRequest()` doesn't work: calls to Profit then fail too. What I remember of why the line is there, is to be compatible with Microsoft's specific implementation of Soap.

**Comment by MegaChriz** [comment] 2022-07-20 07:39
Alright, I've shamelessly copied some logic regarding SOAP from [wyz/practicalafas](https://packagist.org/packages/wyz/practicalafas):

- instances of SoapVar are used instead of SoapParam (taken from https://github.com/rmuit/PracticalAfas/blob/master/src/Client/SoapAppClient.php#L349)
- Soap options "style" and "use" changed (taken from https://github.com/rmuit/PracticalAfas/blob/master/src/Client/SoapAppClient.php#L188)
- Each XML element in the SOAP body is now namespaced.

Before:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="urn:Afas.Profit.Services" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
  <SOAP-ENV:Body>
    <ns1:GetDataWithOptions xmlns="urn:Afas.Profit.Services">
      <connectorId xsi:type="xsd:string">Products</connectorId>
      <options xsi:type="xsd:string">&lt;options&gt;&lt;Outputmode&gt;1&lt;/Outputmode&gt;&lt;Metadata&gt;1&lt;/Metadata&gt;&lt;Outputoptions&gt;2&lt;/Outputoptions&gt;&lt;/options&gt;</options>
      <token xsi:type="xsd:string">&lt;token&gt;&lt;version&gt;1&lt;/version&gt;&lt;data&gt;ABCDEFGHIJK1234&lt;/data&gt;&lt;/token&gt;</token>
      <filtersXml xsi:nil="true"/>
      <skip xsi:type="xsd:int">0</skip>
      <take xsi:type="xsd:string">10</take>
    </ns1:GetDataWithOptions>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

After:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="urn:Afas.Profit.Services">
  <SOAP-ENV:Body>
    <ns1:GetDataWithOptions>
      <ns1:connectorId>Products</ns1:connectorId>
      <ns1:options>&lt;options&gt;&lt;Outputmode&gt;1&lt;/Outputmode&gt;&lt;Metadata&gt;1&lt;/Metadata&gt;&lt;Outputoptions&gt;2&lt;/Outputoptions&gt;&lt;/options&gt;</ns1:options>
      <ns1:token>&lt;token&gt;&lt;version&gt;1&lt;/version&gt;&lt;data&gt;ABCDEFGHIJK1234&lt;/data&gt;&lt;/token&gt;</ns1:token>
      <ns1:filtersXml/>
      <ns1:skip>0</ns1:skip>
      <ns1:take>10</ns1:take>
    </ns1:GetDataWithOptions>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

Let me know if this works for you @boboldehampsink
Code is in https://github.com/MegaChriz/afasprofit/tree/202204_php81_support, and I will merge it to 3.x if you find no further issues.

**Comment by boboldehampsink** [comment] 2022-07-20 09:05
@MegaChriz when using this branch I get the following error:

```
Exception 'Error' with message 'Class "Symfony\Component\EventDispatcher\Event" not found'

in /app/user/vendor/megachriz/afasprofit/src/Core/Event/SendRequestEvent.php:11
```

**Comment by MegaChriz** [comment] 2022-07-20 09:30
Ah, that's probably because of changes in symfony/event-dispatcher 6 I think. In Symfony 6, the Event class is in an other namespace, `\Symfony\Contracts\EventDispatcher\Event` if I'm not mistaken.
I've only tested so far with version 3 and 4. Thanks for testing!

**Comment by MegaChriz** [comment] 2022-07-20 09:53
I changed the namespace now in the code. Tests still pass with symfony/event-dispatcher 4.4. I ran tests manually with symfony/event-dispatcher 5 and 6 too. I also updated requirements for Symfony components in composer.json. All was still limited to Symfony 4 and before.

Can you try again?

**Comment by boboldehampsink** [comment] 2022-07-20 11:11
This all seems to work

**Comment by boboldehampsink** [comment] 2022-07-20 11:52
Mmm just got this error:

```
TypeError: Afas\Afas::getEventDispatcherClass(): Return value must be of type ?string, none returned
  File "/vendor/megachriz/afasprofit/src/Afas.php", line 110, in Afas\Afas::getEventDispatcherClass
    }
  File "/vendor/megachriz/afasprofit/src/Afas.php", line 167, in Afas\Afas::setDefaultContainer
    $event_dispatcher_class = static::getEventDispatcherClass();
  File "/vendor/megachriz/afasprofit/src/Afas.php", line 55, in Afas\Afas::getContainer
    static::setDefaultContainer();
  File "/vendor/megachriz/afasprofit/src/Afas.php", line 84, in Afas\Afas::service
    return static::getContainer()->get($id);
  File "/vendor/megachriz/afasprofit/src/Core/Query/Query.php", line 37, in Afas\Core\Query\Query::getClient
    return Afas::service('afas.soap_client_factory')->create($this->server);
...
```

**Comment by MegaChriz** [comment] 2022-07-20 13:00
Okay, I think `NULL` must explicitly returned when there is no event dispatcher class found. In Symfony 6, the full classname is still "Symfony\Component\EventDispatcher\EventDispatcher", so I assume that the error only happens when symfony/event-dispatcher is not installed. Is that the case in the situation where you got that error?

I committed a small change.

**Comment by boboldehampsink** [comment] 2022-07-21 06:05
Mmm composer update doesn't update this branch to 344e95f346beb51f520e41707ac19cbd1b22fced

**Comment by boboldehampsink** [comment] 2022-07-22 09:41
@MegaChriz could you bump this in packagist so I can test?

**Comment by MegaChriz** [comment] 2022-07-22 09:42
I clicked the "Update" button on Packagist, does that help?

**Comment by boboldehampsink** [comment] 2022-07-22 09:45
That worked!

**Comment by boboldehampsink** [comment] 2022-07-22 09:52
It all seems to work fine now on 8.1

**Comment by 89peter** [comment] 2022-09-20 14:31
Tested on PHP8.1 and works fine here too. Nice work, thank you.

@MegaChriz Could you please create a new release for this branch? I tried to create a pull request but Github says I can't, guess I need to be a contributor.

Cheers

**Comment by MegaChriz** [comment] 2022-09-20 14:34
I was planning to include an other update in a new release too (updates to UpdateConnector XML schemes), but did not get to that yet. I shall create a task for it in my agenda.

**Comment by 89peter** [comment] 2022-09-21 05:56
That's great, thank you. Any idea when you'll be able to tag the release?

**Comment by MegaChriz** [comment] 2022-09-21 07:08
@89peter Ideally I would like to check with a live site for any regressions after the UpdateConnector XML schemes update before creating a new release. I've updated the schemes locally already and pushed these to that live site. Let's see if that results into any errors.

If all goes well, I could perhaps tag the release today. But it depends on if any urgent tasks will popup today.

If the update connector scheme update does result into errors, I will tag the release without that.

**Comment by 89peter** [comment] 2022-09-21 08:24
Got a branch for that? I'm happy to help testing.

**Comment by MegaChriz** [comment] 2022-09-21 09:12
@89peter I've committed it all to the 3.x branch now. I'm thinking of creating a _release candiate_ instead, because I discovered that I hadn't deployed the changes for PHP 8.1 compatibility to a live site yet. I want to make sure that there are no regressions in the release.

**Comment by MegaChriz** [comment] 2022-10-05 14:01
A new release has been created!
https://github.com/MegaChriz/afasprofit/releases/tag/3.2.0

**Closed as completed by MegaChriz** 2022-10-05 14:01 UTC
